services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.windows
    container_name: aca-backend
    isolation: hyperv
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=dev_secret_change_me
      - DB_FILE=C:\\data\\db.sqlite
      - RUNNER_URL=http://runner:5001
      - SUBMISSIONS_DIR=C:\\data\\submissions
      - RESULTS_DIR=C:\\data\\results
      - TASKS_DIR=C:\\tasks
    volumes:
      - .\\data:C:\\data
      - .\\tasks:C:\\tasks:ro
    ports:
      - "3000:3000"
    depends_on:
      - runner

  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile.windows
    container_name: aca-runner
    isolation: hyperv
    environment:
      - PORT=5001
      - BACKEND_URL=http://backend:3000
      - SUBMISSIONS_DIR=C:\\data\\submissions
      - RESULTS_DIR=C:\\data\\results
      - TASKS_DIR=C:\\tasks
    volumes:
      - .\\data:C:\\data
      - .\\tasks:C:\\tasks:ro
    ports:
      - "5001:5001"

  # Frontend placeholder omitted on Windows containers to avoid IIS setup

networks:
  default:
    name: aca-net


